# Generated by Django 5.2.4 on 2025-07-10 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='testdata/%Y/%m/%d/', verbose_name='数据文件')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='testcases.testcase', verbose_name='关联测试用例')),
            ],
            options={
                'verbose_name': '测试数据文件',
                'verbose_name_plural': '测试数据文件',
            },
        ),
    ]
