# Generated by Django 5.2.4 on 2025-07-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mockapi',
            name='unique_mock_path_method',
        ),
        migrations.AlterUniqueTogether(
            name='mockapi',
            unique_together={('path', 'method')},
        ),
    ]
