# Generated by Django 5.2.4 on 2025-07-10 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_initial'),
        ('testcases', '0003_testdatafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：回归测试 2025-01-10', max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '执行失败')], default='running', max_length=20, verbose_name='执行状态')),
                ('total_tests', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_tests', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_tests', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('error_tests', models.IntegerField(default=0, verbose_name='错误用例数')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='执行描述')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('test_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='testcases.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_test.testrun', verbose_name='测试执行记录'),
        ),
    ]
