# Generated by Django 5.2.4 on 2025-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_testrun_apitestresult_test_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
    ]
