# Generated by Django 5.2.4 on 2025-07-15 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_testrun_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
