# Generated by Django 5.2.3 on 2025-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('url', models.CharField(max_length=500, verbose_name='接口URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.TextField(default='{}', help_text='JSON格式', verbose_name='请求头')),
                ('params', models.TextField(default='{}', help_text='JSON格式', verbose_name='URL参数')),
                ('body', models.TextField(default='{}', help_text='JSON格式', verbose_name='请求体')),
                ('description', models.TextField(blank=True, verbose_name='接口描述')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='所属模块')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('headers', models.TextField(default='{}', help_text='JSON格式，会覆盖接口定义的请求头', verbose_name='请求头')),
                ('params', models.TextField(default='{}', help_text='JSON格式，会覆盖接口定义的参数', verbose_name='URL参数')),
                ('body', models.TextField(default='{}', help_text='JSON格式，会覆盖接口定义的请求体', verbose_name='请求体')),
                ('assertions', models.TextField(default='[]', help_text='JSON格式的断言规则列表', verbose_name='断言规则')),
                ('variables', models.TextField(default='{}', help_text='JSON格式的变量定义', verbose_name='变量')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='预期状态码')),
                ('max_response_time', models.IntegerField(blank=True, null=True, verbose_name='最大响应时间(ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='error', max_length=10)),
                ('response_code', models.IntegerField(null=True, verbose_name='响应状态码')),
                ('response_time', models.FloatField(null=True, verbose_name='响应时间(ms)')),
                ('response_body', models.TextField(blank=True, verbose_name='响应内容')),
                ('response_headers', models.TextField(default='{}', help_text='JSON格式', verbose_name='响应头')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('assertion_results', models.TextField(default='[]', help_text='JSON格式', verbose_name='断言结果详情')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
