# Generated by Django 5.2.3 on 2025-06-28 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apidefinition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_test.apidefinition'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_test.apitestcase'),
        ),
    ]
